### ISSUE TITLE
ModuleNotFoundError: No module named 'undetected_chromedriver'

### ISSUE THREAD

**Issue by johentsch** [ferru97/PyPaperBot#72]
After pip-installing PPB on a Windows 11 machine without Chrome browser installed and running any command, the exception cited in the title is thrown. For example:

```
>>> C:\Users\user>python -m PyPaperBot --query query
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\miniconda3\Lib\site-packages\PyPaperBot\__main__.py", line 11, in <module>
    from .Scholar import ScholarPapersInfo
  File "C:\Users\user\miniconda3\Lib\site-packages\PyPaperBot\Scholar.py", line 4, in <module>
    import undetected_chromedriver as uc
ModuleNotFoundError: No module named 'undetected_chromedriver'
```
I managed to fix it by running `pip install undetected_chromedriver` so I guess it simply needs to be added to the dependencies.

**Comment by MaNikhilHo** [comment]
If someone still stumbles upon this issue, you might have to use an older version of python and then run it.
` python3.10 -m venv venv310 |
source venv310/bin/activate |
pip install undetected-chromedriver PyPaperBot
`
it did not work with python 3.17 but is working with 3.10
